"""init_3_0

Revision ID: c5eda377c15d
Revises: 
Create Date: 2026-09-19 23:42:23.508238
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'c5eda377c15d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('oauth_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('access_token_encrypted', sa.String(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_accounts_id'), 'oauth_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_user_id'), 'oauth_accounts', ['user_id'], unique=False)
    op.create_table('research_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='sessionstatus'), nullable=False),
    sa.Column('source_policy', sa.Enum('source_only', 'source_first', name='sourcepolicy'), nullable=False),
    sa.Column('mode', sa.Enum('ask', 'research', name='sessionmode'), nullable=False),
    sa.Column('session_summary', sa.String(), nullable=True),
    sa.Column('memory_summary', sa.String(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_sessions_id'), 'research_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_research_sessions_user_id'), 'research_sessions', ['user_id'], unique=False)
    op.create_table('sources',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('pdf', 'website', 'youtube', 'github', 'notion', 'txt', 'markdown', 'docx', 'web_search_result', name='sourcetype'), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('canonical_uri', sa.String(length=1024), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'indexed', 'failed', 'stale', name='sourcestatus'), nullable=False),
    sa.Column('content_hash', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('content_text', sa.String(), nullable=True),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_index(op.f('ix_sources_user_id'), 'sources', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='messagerole'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'streaming', 'completed', 'failed', name='messagestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('processing', 'completed', 'failed', name='ingestionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_id'), 'ingestion_runs', ['id'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_source_id'), 'ingestion_runs', ['source_id'], unique=False)
    op.create_table('research_events',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_events_id'), 'research_events', ['id'], unique=False)
    op.create_index(op.f('ix_research_events_session_id'), 'research_events', ['session_id'], unique=False)
    op.create_table('research_summaries',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary_markdown', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_summaries_id'), 'research_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_research_summaries_session_id'), 'research_summaries', ['session_id'], unique=False)
    op.create_table('session_sources',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'source_id')
    )
    op.create_table('source_chunks',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_chunks_id'), 'source_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_source_chunks_source_id'), 'source_chunks', ['source_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('node_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_id'), 'agent_runs', ['id'], unique=False)
    op.create_index(op.f('ix_agent_runs_session_id'), 'agent_runs', ['session_id'], unique=False)
    op.create_table('evidence',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_chunk_id', sa.UUID(), nullable=True),
    sa.Column('claim', sa.String(), nullable=False),
    sa.Column('supporting_excerpt', sa.String(), nullable=False),
    sa.Column('support_status', sa.Enum('supported', 'partially_supported', 'unsupported', 'contradicted', name='supportstatus'), nullable=False),
    sa.Column('confidence_label', sa.Enum('high', 'medium', 'low', name='confidencelabel'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['source_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_session_id'), 'evidence', ['session_id'], unique=False)
    op.create_index(op.f('ix_evidence_source_id'), 'evidence', ['source_id'], unique=False)
    op.create_table('session_memories',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('summary', 'preference', 'research_context', 'open_question', name='memorytype'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('source_message_id', sa.UUID(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['chat_messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_memories_id'), 'session_memories', ['id'], unique=False)
    op.create_index(op.f('ix_session_memories_session_id'), 'session_memories', ['session_id'], unique=False)
    op.create_table('web_search_runs',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='websearchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_search_runs_id'), 'web_search_runs', ['id'], unique=False)
    op.create_index(op.f('ix_web_search_runs_message_id'), 'web_search_runs', ['message_id'], unique=False)
    op.create_index(op.f('ix_web_search_runs_session_id'), 'web_search_runs', ['session_id'], unique=False)
    op.create_table('message_citations',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('citation_index', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('locator', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_citations_id'), 'message_citations', ['id'], unique=False)
    op.create_index(op.f('ix_message_citations_message_id'), 'message_citations', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_citations_source_id'), 'message_citations', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_citations_source_id'), table_name='message_citations')
    op.drop_index(op.f('ix_message_citations_message_id'), table_name='message_citations')
    op.drop_index(op.f('ix_message_citations_id'), table_name='message_citations')
    op.drop_table('message_citations')
    op.drop_index(op.f('ix_web_search_runs_session_id'), table_name='web_search_runs')
    op.drop_index(op.f('ix_web_search_runs_message_id'), table_name='web_search_runs')
    op.drop_index(op.f('ix_web_search_runs_id'), table_name='web_search_runs')
    op.drop_table('web_search_runs')
    op.drop_index(op.f('ix_session_memories_session_id'), table_name='session_memories')
    op.drop_index(op.f('ix_session_memories_id'), table_name='session_memories')
    op.drop_table('session_memories')
    op.drop_index(op.f('ix_evidence_source_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_session_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_agent_runs_session_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_source_chunks_source_id'), table_name='source_chunks')
    op.drop_index(op.f('ix_source_chunks_id'), table_name='source_chunks')
    op.drop_table('source_chunks')
    op.drop_table('session_sources')
    op.drop_index(op.f('ix_research_summaries_session_id'), table_name='research_summaries')
    op.drop_index(op.f('ix_research_summaries_id'), table_name='research_summaries')
    op.drop_table('research_summaries')
    op.drop_index(op.f('ix_research_events_session_id'), table_name='research_events')
    op.drop_index(op.f('ix_research_events_id'), table_name='research_events')
    op.drop_table('research_events')
    op.drop_index(op.f('ix_ingestion_runs_source_id'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_sources_user_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_research_sessions_user_id'), table_name='research_sessions')
    op.drop_index(op.f('ix_research_sessions_id'), table_name='research_sessions')
    op.drop_table('research_sessions')
    op.drop_index(op.f('ix_oauth_accounts_user_id'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_id'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
